spring.application.name=stable
# PostgreSQL Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/photography_db
spring.datasource.username=postgres
spring.datasource.password=0911

# Hibernate (JPA) Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect